# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'StitchSDK', '= 6.0.1'
  pod 'FacebookCore'
  pod 'FacebookLogin'

  # Pods for Todo
end
